# Generated by Django 5.2.16 on 2026-07-17 13:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalAuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.BigIntegerField()),
                ('from_status', models.IntegerField(blank=True, null=True)),
                ('to_status', models.IntegerField()),
                ('chain_tx_hash', models.CharField(max_length=66)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalCache',
            fields=[
                ('proposal_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dao_id', models.BigIntegerField()),
                ('contributor', models.CharField(max_length=42)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deliverable_criteria', models.TextField()),
                ('requested_amount', models.CharField(max_length=80)),
                ('deadline', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('yes_weight', models.CharField(default='0', max_length=80)),
                ('no_weight', models.CharField(default='0', max_length=80)),
                ('reclaim_yes_weight', models.CharField(default='0', max_length=80)),
                ('reclaim_no_weight', models.CharField(default='0', max_length=80)),
                ('reclaim_round', models.IntegerField(default=0)),
                ('escrowed_amount', models.CharField(default='0', max_length=80)),
                ('deliverable_url', models.URLField(blank=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('verdict_summary', models.TextField(blank=True)),
                ('screening_rejection_reason', models.TextField(blank=True)),
                ('reclaim_reason', models.TextField(blank=True)),
                ('resubmission_count', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vote_ends_at', models.DateTimeField(blank=True, null=True)),
                ('reclaim_vote_ends_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('search_vector', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.proposalcache')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_hidden', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='proposals.proposalcache')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dao_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deliverable_criteria', models.TextField()),
                ('requested_amount', models.CharField(max_length=80)),
                ('deadline', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.BigIntegerField()),
                ('voter_address', models.CharField(max_length=42)),
                ('vote_type', models.CharField(max_length=20)),
                ('reclaim_round', models.IntegerField(default=0)),
                ('support', models.BooleanField()),
                ('weight', models.CharField(max_length=80)),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('proposal_id', 'voter_address', 'vote_type', 'reclaim_round')},
            },
        ),
    ]
