# Generated by Django 5.2.16 on 2026-07-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalcache',
            name='escrowed_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='proposalcache',
            name='no_weight',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='proposalcache',
            name='reclaim_no_weight',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='proposalcache',
            name='reclaim_yes_weight',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='proposalcache',
            name='requested_amount',
            field=models.DecimalField(decimal_places=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='proposalcache',
            name='yes_weight',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='proposaldraft',
            name='requested_amount',
            field=models.DecimalField(decimal_places=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='votecache',
            name='weight',
            field=models.DecimalField(decimal_places=0, max_digits=78),
        ),
    ]
