# Generated by Django 5.2.16 on 2026-07-20 08:18

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_alter_proposalcache_escrowed_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalcache',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='proposalcache',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='proposals_p_search__349550_gin'),
        ),
    ]
