# Generated by Django 5.2.16 on 2026-07-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_alter_proposalcache_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalauditlogentry',
            name='chain_tx_hash',
            field=models.CharField(blank=True, default='', max_length=66),
        ),
    ]
