# Generated by Django 5.2.16 on 2026-07-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_alter_proposalauditlogentry_chain_tx_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposaldraft',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposaldraft',
            name='deliverable_criteria',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='proposaldraft',
            name='requested_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=78, null=True),
        ),
    ]
