# Generated by Django 5.2.16 on 2026-07-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_alter_proposaldraft_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='proposalcache',
            name='proposals_p_search__349550_gin',
        ),
        migrations.RemoveField(
            model_name='proposalcache',
            name='search_vector',
        ),
    ]
