from rest_framework.test import APITestCase
from django.urls import reverse
from rest_framework import status
from django.utils import timezone
from daos.models import DaoCache
from decimal import Decimal
from unittest.mock import patch

class DaoAPITests(APITestCase):
    def setUp(self):
        self.dao1 = DaoCache.objects.create(
            dao_id=1,
            name="Alpha DAO",
            description="First DAO",
            admin="0xadmin",
            quorum_bps=1000,
            approval_threshold_bps=5000,
            voting_period_seconds=86400,
            funding_cap_bps=2000,
            max_resubmissions=3,
            min_criteria_length=10,
            total_balance=Decimal("100"),
            total_voting_power=Decimal("50")
        )
        
        from daos.models import TreasuryStatsSnapshot
        self.snapshot1 = TreasuryStatsSnapshot.objects.create(
            dao_id=1, total_balance=Decimal("100"), member_count=10, active_proposal_count=2,
            snapshot_at=timezone.now() - timezone.timedelta(days=1)
        )
        self.snapshot2 = TreasuryStatsSnapshot.objects.create(
            dao_id=1, total_balance=Decimal("150"), member_count=12, active_proposal_count=3,
            snapshot_at=timezone.now()
        )
        
        from users.models import User
        self.user = User.objects.create(wallet_address="0x123")

    def test_list_daos_public(self):
        # We haven't created the urls yet, let's assume route 'dao-list' is generated by default router
        url = '/api/daos/'
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data['results']), 1)
        self.assertEqual(response.data['results'][0]['name'], "Alpha DAO")

    def test_retrieve_dao_public(self):
        url = f'/api/daos/{self.dao1.dao_id}/'
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data['name'], "Alpha DAO")

    def test_prepare_create_dao(self):
        url = '/api/daos/prepare-create/'
        data = {
            "name": "New DAO",
            "admin": "0xadmin",
            "quorum_bps": 1000,
            "approval_threshold_bps": 5000,
            "voting_period_seconds": 86400,
            "funding_cap_bps": 2000,
            "max_resubmissions": 3,
            "min_criteria_length": 10
        }
        response = self.client.post(url, data)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data['args'][0], "New DAO")

    def test_voting_power_unauthorized(self):
        url = '/api/daos/1/voting-power/me/'
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

    @patch('indexer.sync._get_genlayer_client')
    def test_voting_power_authorized(self, mock_get_client):
        url = '/api/daos/1/voting-power/me/'
        self.client.force_authenticate(user=self.user)
        mock_get_client.return_value.read_contract.return_value = 100
        response = self.client.get(url)
        self.assertIn('voting_power', response.data)
        self.assertEqual(response.data['voting_power'], "100")

    @patch('indexer.sync._sync_single_dao')
    @patch('indexer.sync._get_genlayer_client')
    def test_voting_power_cache_invalidation(self, mock_get_client, mock_sync_single_dao):
        url = '/api/daos/1/voting-power/me/'
        self.client.force_authenticate(user=self.user)

        # 1. First call caches "100"
        mock_get_client.return_value.read_contract.return_value = 100
        response1 = self.client.get(url)
        self.assertEqual(response1.status_code, status.HTTP_200_OK)
        self.assertEqual(response1.data['voting_power'], "100")

        # 2. Change mock to "200" but don't clear cache yet. 
        # A direct call should still return cached "100".
        mock_get_client.return_value.read_contract.return_value = 200
        response2 = self.client.get(url)
        self.assertEqual(response2.data['voting_power'], "100")

        # 3. Simulate sync-request which invalidates the cache
        from indexer.sync import sync_entity
        sync_entity("dao", 1, self.user.wallet_address)

        # 4. Third call should fetch fresh data "200"
        response3 = self.client.get(url)
        self.assertEqual(response3.data['voting_power'], "200")

    def test_treasury_stats(self):
        url = '/api/daos/1/treasury/stats/'
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data['total_balance'], '150')
        self.assertEqual(response.data['member_count'], 12)

    def test_treasury_history(self):
        url = '/api/daos/1/treasury/history/'
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data['results']), 2)
        self.assertEqual(response.data['results'][0]['id'], self.snapshot2.id)
        self.assertEqual(response.data['results'][1]['id'], self.snapshot1.id)

    def test_prepare_create(self):
        url = '/api/daos/prepare-create/'
        data = {
            "name": "Beta DAO",
            "description": "Second DAO",
            "admin": "0xadmin2",
            "quorum_bps": 1000,
            "approval_threshold_bps": 5000,
            "voting_period_seconds": 86400,
            "funding_cap_bps": 2000,
            "max_resubmissions": 3,
            "min_criteria_length": 10
        }
        response = self.client.post(url, data)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertIn("args", response.data)
        # Should be formatted into the GenLayer args array structure, which is simply a list/dict in this case.
        # It should match the 9 inputs.
        self.assertEqual(len(response.data["args"]), 9)
        self.assertEqual(response.data["args"][0], "Beta DAO")
