# Generated by Django 5.2.16 on 2026-07-20 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawStateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=20)),
                ('entity_id', models.BigIntegerField()),
                ('raw_payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('trigger_source', models.CharField(default='celery_beat', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='RawChainEvent',
        ),
        migrations.RemoveField(
            model_name='synccursor',
            name='last_processed_block_or_tx',
        ),
        migrations.RemoveField(
            model_name='synccursor',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='synccursor',
            name='is_syncing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='synccursor',
            name='last_full_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synccursor',
            name='last_polled_dao_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synccursor',
            name='last_polled_proposal_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synccursor',
            name='syncing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='rawstatesnapshot',
            index=models.Index(fields=['entity_type', 'entity_id', 'fetched_at'], name='indexer_raw_entity__89be97_idx'),
        ),
    ]
