from django.urls import reverse
from rest_framework.test import APITestCase
from rest_framework import status
from django.core.cache import cache
from users.models import User
from daos.models import DaoCache
from proposals.models import ProposalCache, ProposalDraft, Notification
from indexer.sync import _get_genlayer_client
from unittest.mock import patch

class ThrottleTests(APITestCase):
    def setUp(self):
        self.user = User.objects.create(wallet_address='0x123')
        self.client.force_authenticate(user=self.user)
        
        # Clear cache to reset rate limiters
        cache.clear()

        self.dao = DaoCache.objects.create(
            dao_id=1, 
            name="Test DAO",
            quorum_bps=1000,
            approval_threshold_bps=5000,
            voting_period_seconds=86400,
            funding_cap_bps=1000,
            max_resubmissions=2,
            min_criteria_length=100,
            admin="0x123",
            total_voting_power=10000
        )
        from django.utils import timezone
        self.proposal = ProposalCache.objects.create(proposal_id=1, dao_id=1, title="Test", status=0, contributor="0x123", requested_amount=100, deadline=timezone.now())
        self.draft = ProposalDraft.objects.create(dao_id=1, contributor=self.user, title="Draft")

    def test_rpc_call_throttle(self):
        url = reverse('dao-latest-dao') # Generated by router
        # Mock the RPC call to just return 404 to avoid actual network call
        with patch('indexer.sync._get_genlayer_client') as mock_client:
            mock_client.return_value.read_contract.return_value = 0
            
            for _ in range(10):
                response = self.client.post(url)
                self.assertNotEqual(response.status_code, status.HTTP_429_TOO_MANY_REQUESTS)
            
            response = self.client.post(url)
            self.assertEqual(response.status_code, status.HTTP_429_TOO_MANY_REQUESTS)

    def test_comment_throttle(self):
        url = reverse('proposal-comments', kwargs={'pk': self.proposal.pk})
        data = {'body': 'test comment'}
        
        for _ in range(20):
            response = self.client.post(url, data)
            self.assertNotEqual(response.status_code, status.HTTP_429_TOO_MANY_REQUESTS)
        
        response = self.client.post(url, data)
        self.assertEqual(response.status_code, status.HTTP_429_TOO_MANY_REQUESTS)

    def test_draft_throttle(self):
        url = reverse('dao-draft-list', kwargs={'dao_id': self.dao.dao_id})
        data = {'title': 'draft'}
        
        for _ in range(30):
            response = self.client.post(url, data)
            self.assertNotEqual(response.status_code, status.HTTP_429_TOO_MANY_REQUESTS)
        
        response = self.client.post(url, data)
        self.assertEqual(response.status_code, status.HTTP_429_TOO_MANY_REQUESTS)

    def test_prepare_submit_throttle(self):
        url = reverse('dao-prepare-create')
        data = {'name': 'Test DAO', 'quorum_bps': 100, 'approval_threshold_bps': 100, 'voting_period_seconds': 3600}
        
        for _ in range(20):
            response = self.client.post(url, data)
            self.assertNotEqual(response.status_code, status.HTTP_429_TOO_MANY_REQUESTS)
        
        response = self.client.post(url, data)
        self.assertEqual(response.status_code, status.HTTP_429_TOO_MANY_REQUESTS)

    def test_notification_throttle(self):
        url = reverse('notification-mark-all-read')
        
        for _ in range(30):
            response = self.client.post(url)
            self.assertNotEqual(response.status_code, status.HTTP_429_TOO_MANY_REQUESTS)
        
        response = self.client.post(url)
        self.assertEqual(response.status_code, status.HTTP_429_TOO_MANY_REQUESTS)
