# Generated by Django 5.2.16 on 2026-07-17 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaoCache',
            fields=[
                ('dao_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('admin', models.CharField(max_length=42)),
                ('quorum_bps', models.IntegerField()),
                ('approval_threshold_bps', models.IntegerField()),
                ('voting_period_seconds', models.IntegerField()),
                ('funding_cap_bps', models.IntegerField()),
                ('max_resubmissions', models.IntegerField()),
                ('min_criteria_length', models.IntegerField()),
                ('total_balance', models.CharField(default='0', max_length=80)),
                ('total_voting_power', models.CharField(default='0', max_length=80)),
                ('proposal_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreasuryStatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dao_id', models.BigIntegerField()),
                ('total_balance', models.CharField(max_length=80)),
                ('member_count', models.IntegerField(default=0)),
                ('active_proposal_count', models.IntegerField(default=0)),
                ('snapshot_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
