# Generated by Django 5.2.16 on 2026-07-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daocache',
            name='total_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='daocache',
            name='total_voting_power',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='treasurystatssnapshot',
            name='total_balance',
            field=models.DecimalField(decimal_places=0, max_digits=78),
        ),
    ]
