# Generated by Django 5.2.16 on 2026-07-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daos', '0002_alter_daocache_total_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daocache',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DaoMemberCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dao_id', models.BigIntegerField()),
                ('member_address', models.CharField(max_length=42)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dao_id'], name='daos_daomem_dao_id_30cdf4_idx'), models.Index(fields=['member_address'], name='daos_daomem_member__87a225_idx')],
                'unique_together': {('dao_id', 'member_address')},
            },
        ),
    ]
